# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

jobs:
  - job: linux_chrome
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm ci
        npm run install-selenium
      displayName: 'npm install and install selenium'

    - script: |
        npm run test:chrome
      displayName: 'Run test with chrome'

  - job: linux_firefox
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - script: |
          npm ci
          npm run install-selenium
        displayName: 'npm install and install selenium'

      - script: |
          npm run test:firefox
        displayName: 'Run test with chrome'

  - job: macos_safari
    pool:
      vmImage: 'macOS-10.13'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - script: |
          npm ci
          npm run install-selenium
        displayName: 'npm install and install selenium'

      - script: |
          npm run test:safari
        displayName: 'Run test with safari'
